### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by rk85097** [george-lim/zoom-sdk-guide#1]
Hello, 

While it is understandable why you cannot support Bitcode, are there any plans to support it eventually? What dependencies blocks you from achieving this? 

Thanks,
Roy.

**Comment by george-lim** [comment]
Hi! Unfortunately, this is a discovered issue with Zoom's MobileRTC framework. It does not support Bitcode as far as I know. As I don't work for Zoom, I cannot view / modify their codebase to support Bitcode.
